#!/bin/sh
#
# buildcross - a tool for building GCC cross toolchains
# Copyright (C) 2019-2021  Mikael Pettersson
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Usage: buildcross [-jN] <TARGET> [<CROSS_DIR>]
#
# Supported targets and resulting toolchains:
#
# a29k		a29k-unknown-coff (no libc)
# aarch64	aarch64-unknown-linux-gnu
# alpha		alpha-unknown-linux-gnu
# arc		arc-unknown-linux-gnu
# armv7l	armv7l-unknown-linux-gnueabi
# avr		avr-unknown-elf (no libc)
# bfin		bfin-unknown-linux-uclibc
# bpf		bpf-unknown-none (no libc)
# c6x		c6x-unknown-uclinux
# cr16		cr16-unknown-elf (no libc)
# cris		crisv32-unknown-linux-uclibc
# crx		crx-unknown-elf (no libc)
# csky		csky-unknown-linux-gnu (only little-endian)
# d30v		d30v-unknown-elf (no libc)
# epiphany	epiphany-unknown-elf (no libc)
# fr30		fr30-unknown-elf
# frv		frv-unknown-linux-uclibc
# ft32		ft32-unknown-elf (no libc)
# h8300		h8300-unknown-linux-uclibc
# hppa		hppa-unknown-linux-gnu (no -m64 support)
# i860		i860-stardent-sysv4 (no libc)
# i960		i960-unknown-coff (no libc)
# ia64		ia64-unknown-linux-gnu
# ip2k		ip2k-unknown-elf (no libc)
# iq2000	iq2000-unknown-elf
# lm32		lm32-unknown-elf
# m32c		m32c-unknown-elf
# m32r		m32r-unknown-elf
# m68k		m68k-unknown-linux-gnu
# m88k		m88k-unknown-coff (no libc)
# mcore		mcore-unknown-elf (no libc)
# mep		mep-unknown-elf (no libc)
# microblaze	microblaze-unknown-linux-gnu
# mingw64	x86_64-w64-mingw32 with -m64 and -m32 support
# mips64	mips64-unknown-linux-gnu with -mabi=64, -mabi=n32, and -mabi=32 support
# mmix		mmix-knuth-mmixware (with newlib)
# mn10300	mn10300-unknown-elf (no libc)
# moxie		moxie-unknown-elf (no libc)
# msp430	msp430-unknown-elf (no libc)
# nds32		nds32le-unknown-elf
# nios2		nios2-unknown-linux-gnu
# ns32k		ns32k-unknown-netbsd (no libc)
# or1k		or1k-unknown-linux-musl
# pdp11		pdp11-unknown-aout (no libc)
# ppc64		ppc64-unknown-linux-gnu with -m64 and -m32 support
# ppc64le	ppc64le-unknown-linux-gnu (no -m32 support)
# pru		pru-unknown-elf
# rl78		rl78-unknown-elf
# riscv64	riscv64-unknown-linux-gnu (no 32-bit support)
# rx		rx-unknown-elf
# s390x		s390x-unknown-linux-gnu with -m64 and -m31 support
# score		score-unknown-elf (no libc)
# sh4		sh4-unknown-linux-gnu
# sparc64	sparc64-unknown-linux-gnu with -m64 and -m32 support
# tilegx	tilegx-unknown-linux-gnu
# v850		v850-unknown-elf
# vax		vax-unknown-linux (no libc or kernel headers)
# visium	visium-unknown-elf
# x86_64	x86_64-unknown-linux-gnu with -m64, -mx32, and -m32 support
# xstormy16	xstormy16-unknown-elf (no libc)
# xtensa	xtensa-unknown-linux-uclibc
#
# Pending:
#
# aarch64	waiting for glibc -mabi=ilp32 support
# nds32		waiting for glibc support, uclibc-ng does not build against upstream kernel headers
#
# Unsupported:
#
# - targets not supported by upstream toolchain components
# - targets requiring add-on patches
#   (for now, may change time permitting)
# - Linux targets using another libc than glibc, uclibc-ng, or musl
#   (for now, may change time permitting)
# - non-Linux targets except mingw-w64 and plain ELF with newlib
#
# Specific unsupported targets:
#
# amdgcn	not in binutils, though apparently in llvm's assembler and linker
# avr32		not in any upstream toolchain components except uClibc-ng, removed in linux-4.12
# gmicro	not in binutils, removed in gcc-3.0
# hexagon	not in any upstream toolchain components, removed in linux-4.17 (TODO: check llvm)
# kvx		not yet in any upstream toolchain components, except for uClibc-ng
# metag		not in upstream GCC, removed in linux-4.17
# mt		broken in gcc (present in 4.1/4.2/4.3, but they all ICE)
# picochip	not in binutils, removed in gcc-5
# pj		binutils rejects gcc's output and command-line options, did vanilla sources ever work?
# nvptx		not in binutils, requires the nvptx-tools package
# ubicom32	not in any upstream toolchain components or kernel
# unicore32	not in any upstream toolchain components, removed in linux-5.9
# we32k		not in binutils

set -e

VERSION="5.1.0"

case "$1" in
    -j*)
	DASHJ="$1"
	shift
	;;
    *)
	DASHJ=
esac

TARGET_ARCH="$1"
if [ -z "${TARGET_ARCH}" ]; then
    echo no target arch provided
    exit 1
fi

BUILD_DIR=`realpath .`
DOWNLOADS_DIR=`realpath ./downloads`
HOST_TOOLS_DIR=`realpath ./host-tools`
SOURCES_DIR=`realpath ./sources`

CROSS_DIR=${2:-"${BUILD_DIR}/cross-${TARGET_ARCH}"}

# default component versions
BINUTILS_VSN=2.36.1
GCC_VSN=11.1.0
GLIBC_VSN=2.33
GMP_VSN=6.2.1
LINUX_VSN=5.13
MINGW64_VSN=9.0.0
MPC_VSN=1.2.1
MPFR_VSN=4.1.0
MUSL_VSN=1.2.2
NEWLIB_VSN=4.1.0
UCLIBC_VSN=1.0.38

# binutils configuration options
BINUTILS_WANTS_ENABLE_OBSOLETE=

# gcc configuration options
GCC_WANTS_ENABLE_OBSOLETE=

# uClibc-ng configuration options
UCLIBC_WANTS_LINUXTHREADS=
UCLIBC_WANTS_NPTL=
UCLIBC_WANTS_SSP=
UCLIBC_WANTS_LITTLE_ENDIAN=
UCLIBC_WANTS_BIG_ENDIAN=

# target-specfic overrides
case "${TARGET_ARCH}" in
    "a29k")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-coff"
	GCC_VSN=2.95.3
	BINUTILS_VSN=2.16.1
	NEWLIB_VSN= # fails to build for a29k
	# you need to:
	# - adjust PATH to select gcc-3.x (3.4.6 and 3.3.6 are known to work)
	# - set BUILD_TRIPLE because gcc-3.x -v doesn't list Target:
	# - if on x86_64, set CC to a wrapper script that enforces -m32
	# - if on x86_64, set BUILD_TRIPLE=i686-pc-linux-gnu
	SKIP_HOST_TOOLS=1
	;;
    "arc")
	GCC_VSN=10.3.0 # gcc-11.1.0 fails to build glibc-2.33
	;;
    "armv7l")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-linux-gnueabi"
	;;
    "avr")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-elf"
	NEWLIB_VSN= # not supported in newlib at all
	;;
    "bfin")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-linux-uclibc"
	UCLIBC_WANTS_LINUXTHREADS=y
	UCLIBC_WANTS_SSP=y
	LINUX_VSN=4.16 # blackfin was removed in linux-4.17
	GCC_VSN=9.3.0 # gcc-10.2.0 gives linkage errors in uClibc-ng
	;;
    "bpf")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-none"
	NEWLIB_VSN= # not supported in newlib at all
	;;
    "c6x")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-uclinux"
	UCLIBC_WANTS_LINUXTHREADS=y
	UCLIBC_WANTS_SSP=y
	UCLIBC_WANTS_BIG_ENDIAN=y
	LINUX_VSN=5.11 # c6x was removed in linux-5.12
	;;
    "cr16")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-elf"
	NEWLIB_VSN= # newlib gives linkage errors
	;;
    "cris")
	TARGET_TRIPLE="crisv32-unknown-linux-uclibc"
	UCLIBC_WANTS_LINUXTHREADS=y
	UCLIBC_WANTS_SSP=y
	LINUX_VSN=4.16 # cris was removed in linux-4.17
	GCC_WANTS_ENABLE_OBSOLETE=1 # gcc-10 marks cris as obsolete
	GCC_VSN=10.3.0 # gcc-11.1.0 dropped support for this target triple
	;;
    "crx")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-elf"
	GCC_VSN=4.5.4 # 4.6 ICEs, removed in 4.7
	NEWLIB_VSN= # gcc ICEs building newlib
	SKIP_HOST_TOOLS=1
	;;
    "csky")
	GCC_VSN=10.3.0 # gcc-11.1.0 fails to build glibc-2.33
	;;
    "d30v")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-elf"
	GCC_VSN=3.4.6
	GCC_WANTS_ENABLE_OBSOLETE=1
	BINUTILS_VSN=2.16.1
	NEWLIB_VSN= # fails to build for d30v
	# you need to:
	# - adjust PATH to select gcc-3.x (3.3.6 and 3.4.6 are known to work)
	# - set BUILD_TRIPLE because gcc-3.x -v doesn't list Target:
	SKIP_HOST_TOOLS=1
	;;
    "epiphany")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-elf"
	NEWLIB_VSN= # newlib gives linkage errors
	;;
    "fr30")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-elf"
	;;
    "frv")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-linux-uclibc"
	UCLIBC_WANTS_SSP=y
	LINUX_VSN=4.16 # frv was removed in linux-4.17
	;;
    "ft32")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-elf"
	NEWLIB_VSN= # newlib gives linkage errors
	;;
    "h8300")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-linux-uclibc"
	GCC_VSN=10.3.0 # gcc-11.1.0 fails to build uClibc-ng-1.0.38
	;;
    "hppa")
	GCC_VSN=10.3.0 # gcc-11.1.0 fails to build glibc-2.33
	;;
    "i860")
	TARGET_TRIPLE="${TARGET_ARCH}-stardent-sysv4"
	GCC_VSN=3.2.3
	GCC_WANTS_ENABLE_OBSOLETE=1
	BINUTILS_VSN=2.16.1
	NEWLIB_VSN= # doesn't support i860
	SKIP_HOST_TOOLS=1
	# you need to:
	# - adjust PATH to select gcc-3.x (3.3.6 and 3.4.6 are known to work)
	# - set BUILD_TRIPLE because gcc-3.x -v doesn't list Target:
	# - if on x86_64, set CC to a wrapper script that enforces -m32
	;;
    "i960")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-coff"
	GCC_VSN=3.4.6
	GCC_WANTS_ENABLE_OBSOLETE=1
	BINUTILS_VSN=2.16.1
	NEWLIB_VSN= # fails to build for i960
	# you need to:
	# - adjust PATH to select gcc-3.x (3.3.6 and 3.4.6 are known to work)
	# - set BUILD_TRIPLE because gcc-3.x -v doesn't list Target:
	# - if on x86_64, set CC to a wrapper script that enforces -m32
	SKIP_HOST_TOOLS=1
	;;
    "ia64")
	BINUTILS_WANTS_ENABLE_OBSOLETE=1 # binutils-2.36 marks ia64 as obsolete
	;;
    "ip2k")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-elf"
	GCC_VSN=3.3.6 # added in 3.3, ICEs in 3.4 and 4.0, removed in 4.1
	NEWLIB_VSN= # doesn't support ip2k
	# you need to:
	# - adjust PATH to select gcc-3.x (3.3.6 and 3.4.6 are known to work)
	# - set BUILD_TRIPLE because gcc-3.x -v doesn't list Target:
	SKIP_HOST_TOOLS=1
	;;
    "iq2000")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-elf"
	;;
    "lm32")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-elf"
	;;
    "m32c")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-elf"
	GCC_VSN=4.7.4 # later ones fail in various ways
	SKIP_HOST_TOOLS=1
	;;
    "m32r")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-elf"
	;;
    "m88k")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-coff"
	GCC_VSN=2.95.3
	BINUTILS_VSN=2.16.1
	NEWLIB_VSN= # fails to build for m88k
	# you need to:
	# - adjust PATH to select gcc-3.x (3.4.6 and 3.3.6 are known to work)
	# - set BUILD_TRIPLE because gcc-3.x -v doesn't list Target:
	# - if on x86_64, set CC to a wrapper script that enforces -m32
	# - if on x86_64, set BUILD_TRIPLE=i686-pc-linux-gnu
	SKIP_HOST_TOOLS=1
	;;
    "mcore")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-elf"
	NEWLIB_VSN= # newlib gives linkage errors
	;;
    "mep")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-elf"
	GCC_VSN=4.5.4 # later ones are broken, removed in gcc-7
	NEWLIB_VSN= # fails to build for mep
	SKIP_HOST_TOOLS=1
	;;
    "microblaze")
	GCC_VSN=10.3.0 # gcc-11.1.0 fails to build glibc-2.33
	;;
    "mingw64")
	TARGET_TRIPLE="x86_64-w64-mingw32"
	;;
    "mips64")
	GCC_VSN=10.3.0 # gcc-11.1.0 fails to build glibc-2.33
	;;
    "mmix")
	TARGET_TRIPLE="${TARGET_ARCH}-knuth-mmixware"
	;;
    "mn10300")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-elf"
	NEWLIB_VSN= # newlib gives linkage errors
	;;
    "moxie")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-elf"
	NEWLIB_VSN= # newlib gives linkage errors
	;;
    "msp430")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-elf"
	NEWLIB_VSN= # newlib gives linkage errors
	;;
    "nds32")
	TARGET_TRIPLE="nds32le-unknown-elf"
	;;
    "nios2")
	GCC_VSN=10.3.0 # gcc-11.1.0 fails to build glibc-2.33
	;;
    "ns32k")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-netbsd"
	GCC_VSN=4.0.4
	GCC_WANTS_ENABLE_OBSOLETE=1 # obsoleted in 4.0, removed in 4.1
	SKIP_HOST_TOOLS=1 # PATH must point to a suitable old gcc
	# we can't build libc, but netbsd-1.5.3's can be popped in
	;;
    "or1k")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-linux-musl"
	;;
    "pdp11")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-aout"
	NEWLIB_VSN= # not supported in newlib at all
	;;
    "ppc64")
	GCC_VSN=10.3.0 # gcc-11.1.0 fails to build glibc-2.33
	;;
    "ppc64le")
	GCC_VSN=10.3.0 # gcc-11.1.0 fails to build glibc-2.33
	;;
    "pru")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-elf"
	;;
    "riscv64")
	GCC_VSN=10.3.0 # gcc-11.1.0 fails to build glibc-2.33
	;;
    "rl78")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-elf"
	;;
    "rx")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-elf"
	;;
    "s390x")
	GCC_VSN=10.3.0 # gcc-11.1.0 fails to build glibc-2.33
	;;
    "score")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-elf"
	GCC_VSN=4.9.4 # removed in gcc-5.0
	GCC_WANTS_ENABLE_OBSOLETE=1
	NEWLIB_VSN= # doesn't support score
	SKIP_HOST_TOOLS=1 # PATH must point to a suitable old gcc
	;;
    "sh4")
	GCC_VSN=10.3.0 # gcc-11.1.0 fails to build glibc-2.33
	;;
    "tilegx")
	BINUTILS_VSN=2.28.1 # later versions cannot build glibc
	GCC_VSN=7.5.0 # later versions cannot build glibc
	GLIBC_VSN=2.25 # later versions do not build
	LINUX_VSN=4.16 # tile was removed in linux-4.17
	;;
    "v850")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-elf"
	;;
    "vax")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-linux"
	NEWLIB_VSN= # not in any supported libc
	;;
    "visium")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-elf"
	;;
    "xstormy16")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-elf"
	NEWLIB_VSN= # newlib gives linkage errors
	;;
    "xtensa")
	TARGET_TRIPLE="${TARGET_ARCH}-unknown-linux-uclibc"
	UCLIBC_WANTS_NPTL=y
	UCLIBC_WANTS_SSP=y
	;;
esac

if [ -z "${TARGET_TRIPLE}" ]; then
    TARGET_TRIPLE="${TARGET_ARCH}-unknown-linux-gnu"
fi

# disable the components we don't want
case "${TARGET_TRIPLE}" in
    *linux-gnu*)
	UCLIBC_VSN=
	MUSL_VSN=
	MINGW64_VSN=
	NEWLIB_VSN=
	;;
    *linux-uclibc* | *uclinux*)
	GLIBC_VSN=
	MUSL_VSN=
	MINGW64_VSN=
	NEWLIB_VSN=
	;;
    *linux-musl*)
	GLIBC_VSN=
	UCLIBC_VSN=
	LINUX_VSN=
	MINGW64_VSN=
	NEWLIB_VSN=
	;;
    x86_64-w64-mingw32)
	GLIBC_VSN=
	UCLIBC_VSN=
	MUSL_VSN=
	LINUX_VSN=
	NEWLIB_VSN=
	;;
    *-elf | \
    a29k-unknown-coff | \
    bpf-unknown-none | \
    i860-stardent-sysv4 | \
    i960-unknown-coff | \
    m88k-unknown-coff | \
    ns32k-unknown-netbsd | \
    mmix-knuth-mmixware | \
    pdp11-unknown-aout | \
    vax-unknown-linux)
	GLIBC_VSN=
	UCLIBC_VSN=
	MUSL_VSN=
	MINGW64_VSN=
	LINUX_VSN=
	;;
esac

log() {
    echo
    echo "@ $1"
    echo
}

DISTFILES="https://mirrors.kernel.org/gentoo/distfiles"

get_tarball() {
    local EXT=${2:-"xz"}
    local URL=${3:-"${DISTFILES}"}
    local ALT_URL="$4"
    if [ ! \( -f "$1.tar.xz" -o -f "$1.tar.bz2" -o -f "$1.tar.gz" \) ]; then
	wget "${URL}/$1.tar.${EXT}" || :
	if [ ! -f "$1.tar.${EXT}" ]; then
	    if [ -n "${ALT_URL}" ]; then
		wget "${ALT_URL}/$1.tar.${EXT}"
	    else
		exit 1
	    fi
	fi
    fi
}

# Gentoo's distfiles doesn't contain all kernel versions,
# so as fallback try to get them directly from upstream.
get_linux_tarball() {
    local LINUX_VSN="$1"
    local KERNEL_DIR=
    case "${LINUX_VSN}" in
	5\.*)
	    KERNEL_DIR=v5.x
	    ;;
	4\.*)
	    KERNEL_DIR=v4.x
	    ;;
    esac
    get_tarball "linux-${LINUX_VSN}" "xz" "${DISTFILES}" "https://www.kernel.org/pub/linux/kernel/${KERNEL_DIR}"
}

get_sources() {
    log "getting sources"
    cd "${DOWNLOADS_DIR}"
    get_tarball "binutils-${BINUTILS_VSN}"
    get_tarball "gcc-${GCC_VSN}"
    [ -n "${GLIBC_VSN}" ] && get_tarball "glibc-${GLIBC_VSN}"
    [ -n "${UCLIBC_VSN}" ] && get_tarball "uClibc-ng-${UCLIBC_VSN}" "xz" "https://downloads.uclibc-ng.org/releases/${UCLIBC_VSN}"
    [ -n "${MUSL_VSN}" ] && get_tarball "musl-${MUSL_VSN}" "gz"
    [ -n "${MINGW64_VSN}" ] && get_tarball "mingw-w64-v${MINGW64_VSN}" "bz2"
    [ -n "${NEWLIB_VSN}" ] && get_tarball "newlib-${NEWLIB_VSN}" "gz"
    get_tarball "gmp-${GMP_VSN}"
    [ -n "${LINUX_VSN}" ] && get_linux_tarball "${LINUX_VSN}"
    get_tarball "mpfr-${MPFR_VSN}"
    get_tarball "mpc-${MPC_VSN}" "gz"
    cd -
}

unpack_tarball() {
    if [ ! -d "${SOURCES_DIR}/$1" ]; then
	if [ -f "${DOWNLOADS_DIR}/$1.tar.xz" ]; then
	    tar -C "${SOURCES_DIR}" -xf "${DOWNLOADS_DIR}/$1.tar.xz"
	elif [ -f "${DOWNLOADS_DIR}/$1.tar.bz2" ]; then
	    tar -C "${SOURCES_DIR}" -xf "${DOWNLOADS_DIR}/$1.tar.bz2"
	else
	    tar -C "${SOURCES_DIR}" -xf "${DOWNLOADS_DIR}/$1.tar.gz"
	fi
    fi
}

build_host_gmp() {
    local SUFFIX="$1"
    if [ -d "${HOST_TOOLS_DIR}/gmp-${GMP_VSN}${SUFFIX}" -o -d "${HOST_TOOLS_DIR}/gcc-${GCC_VSN}" ]; then
	return
    fi
    log "building host gmp-${GMP_VSN}${SUFFIX}"
    unpack_tarball "gmp-${GMP_VSN}"
    rm -rf objdir-gmp
    mkdir objdir-gmp
    cd objdir-gmp
    unset ABI
    ${SOURCES_DIR}/gmp-${GMP_VSN}/configure \
		--prefix="${HOST_TOOLS_DIR}/gmp-${GMP_VSN}${SUFFIX}" \
		--disable-shared \
		--enable-alloca=alloca \
		ABI=64
    make ${DASHJ}
    make install
    cd ..
    rm -rf objdir-gmp
}

build_host_mpfr() {
    local SUFFIX="$1"
    if [ -d "${HOST_TOOLS_DIR}/mpfr-${MPFR_VSN}${SUFFIX}" -o -d "${HOST_TOOLS_DIR}/gcc-${GCC_VSN}" ]; then
	return
    fi
    log "building host mpfr-${MPFR_VSN}${SUFFIX}"
    unpack_tarball "mpfr-${MPFR_VSN}"
    rm -rf objdir-mpfr
    mkdir objdir-mpfr
    cd objdir-mpfr
    ${SOURCES_DIR}/mpfr-${MPFR_VSN}/configure \
		--prefix="${HOST_TOOLS_DIR}/mpfr-${MPFR_VSN}${SUFFIX}" \
		--with-gmp="${HOST_TOOLS_DIR}/gmp-${GMP_VSN}${SUFFIX}" \
		--disable-shared
    make ${DASHJ}
    make install
    cd ..
    rm -rf objdir-mpfr
}

build_host_mpc() {
    local SUFFIX="$1"
    if [ -d "${HOST_TOOLS_DIR}/mpc-${MPC_VSN}${SUFFIX}" -o -d "${HOST_TOOLS_DIR}/gcc-${GCC_VSN}" ]; then
	return
    fi
    log "building host mpc-${MPC_VSN}${SUFFIX}"
    unpack_tarball "mpc-${MPC_VSN}"
    rm -rf objdir-mpc
    mkdir objdir-mpc
    cd objdir-mpc
    ${SOURCES_DIR}/mpc-${MPC_VSN}/configure \
		--prefix="${HOST_TOOLS_DIR}/mpc-${MPC_VSN}${SUFFIX}" \
		--with-gmp="${HOST_TOOLS_DIR}/gmp-${GMP_VSN}${SUFFIX}" \
		--with-mpfr="${HOST_TOOLS_DIR}/mpfr-${MPFR_VSN}${SUFFIX}" \
		--disable-shared
    make ${DASHJ}
    make install
    cd ..
    rm -rf objdir-mpc
}

build_host_gcc() {
    local SUFFIX="$1"
    local MAKE_TARGET
    local DISABLE_BOOTSTRAP
    if [ -d "${HOST_TOOLS_DIR}/gcc-${GCC_VSN}${SUFFIX}" -o -d "${HOST_TOOLS_DIR}/gcc-${GCC_VSN}" ]; then
	return
    fi
    log "building host gcc-${GCC_VSN}${SUFFIX}"
    if [ -z "${SUFFIX}" ]; then
	DISABLE_BOOTSTRAP=
	MAKE_TARGET=bootstrap-lean
    else
	DISABLE_BOOTSTRAP="--disable-bootstrap"
	MAKE_TARGET=
    fi
    unpack_tarball "gcc-${GCC_VSN}"
    rm -rf objdir-gcc
    mkdir objdir-gcc
    cd objdir-gcc
    ${SOURCES_DIR}/gcc-${GCC_VSN}/configure \
		--prefix="${HOST_TOOLS_DIR}/gcc-${GCC_VSN}${SUFFIX}" \
		--with-gmp="${HOST_TOOLS_DIR}/gmp-${GMP_VSN}${SUFFIX}" \
		--with-mpfr="${HOST_TOOLS_DIR}/mpfr-${MPFR_VSN}${SUFFIX}" \
		--with-mpc="${HOST_TOOLS_DIR}/mpc-${MPC_VSN}${SUFFIX}" \
		--without-isl \
		--disable-libgomp \
		--disable-libmpx \
		--disable-libquadmath \
		--disable-libsanitizer \
		--disable-lto \
		--disable-multilib \
		--disable-nls \
		--disable-plugin \
		--disable-shared \
		--enable-checking=release \
		--enable-languages=c,c++ \
		--enable-threads=posix \
		${DISABLE_BOOTSTRAP}
    make ${DASHJ} ${MAKE_TARGET}
    make install
    cd ..
    rm -rf objdir-gcc
}

build_cross_gcc() {
    local STAGE="$1"
    local LIBC_CONFIGS
    local LIBSSP_CONFIG
    local MULTILIB_CONFIG
    local MAKE_TARGET
    local INSTALL_TARGET
    local ENABLE_CHECKING
    local ENABLE_OBSOLETE
    if [ -f "${CROSS_DIR}/.stage-gcc-${STAGE}" ]; then
	return
    fi
    log "building cross-gcc-${GCC_VSN}-${STAGE}"
    LIBC_CONFIGS="--enable-threads=posix"
    LIBSSP_CONFIG="--enable-libssp"
    MULTILIB_CONFIG="--enable-multilib"
    ENABLE_OBSOLETE=
    ENABLE_CHECKING="--enable-checking=release"
    case "${GCC_VSN}" in
	2.* | 3.*)
	    ENABLE_CHECKING= # gcc prior to 4.0 doesn't understand --enable-checking=release
	    ;;
    esac
    ENABLE_OBSOLETE=
    if [ -n "${GCC_WANTS_ENABLE_OBSOLETE}" ]; then
	ENABLE_OBSOLETE="--enable-obsolete"
    fi
    case "${TARGET_ARCH}" in
	"aarch64")
	    LIBSSP_CONFIG="--disable-libssp"
	    MULTILIB_CONFIG="--disable-multilib"
	    ;;
	"arc")
	    MULTILIB_CONFIG="--disable-multilib --with-cpu=hs38"
	    ;;
	"armv7l")
	    MULTILIB_CONFIG="--disable-multilib --with-arch=armv7-a --with-tune=cortex-a9 --with-float=hard --with-fpu=vfpv3-d16"
	    ;;
	"csky")
	    MULTILIB_CONFIG="--disable-multilib --with-endian=little"
	    ;;
	"d30v")
	    # fixincludes requires /usr/include/ to exist, even if empty
	    mkdir -p "${CROSS_DIR}/usr/include"
	    ;;
	"frv")
	    LIBSSP_CONFIG="--disable-libssp"
	    ;;
	"i960")
	    # fixincludes requires /usr/include/ to exist, even if empty
	    mkdir -p "${CROSS_DIR}/usr/include"
	    ;;
	"ia64")
	    MULTILIB_CONFIG="--disable-multilib --with-system-libunwind=yes"
	    ;;
	"ip2k")
	    # fixincludes requires /usr/include/ to exist, even if empty
	    mkdir -p "${CROSS_DIR}/usr/include"
	    ;;
	"mep")
	    mkdir -p "${CROSS_DIR}/usr/include/sys"
	    touch "${CROSS_DIR}/usr/include/sys/types.h"
	    touch "${CROSS_DIR}/usr/include/stdio.h"
	    touch "${CROSS_DIR}/usr/include/errno.h"
	    touch "${CROSS_DIR}/usr/include/string.h"
	    touch "${CROSS_DIR}/usr/include/stdlib.h"
	    touch "${CROSS_DIR}/usr/include/unistd.h"
	    touch "${CROSS_DIR}/usr/include/time.h"
	    ;;
	"mingw64")
	    MULTILIB_CONFIG="--enable-multilib --enable-64bit --with-dwarf"
	    LIBC_CONFIGS="--enable-threads=win32"
	    ;;
	"ns32k")
	    # fixincludes requires /usr/include/ to exist, even if empty
	    # libgcc requires /usr/include/machine/ansi.h to exist, even if empty
	    mkdir -p "${CROSS_DIR}/usr/include/machine"
	    touch "${CROSS_DIR}/usr/include/machine/ansi.h"
	    ;;
	"ppc64le")
	    # see https://sourceware.org/bugzilla/show_bug.cgi?id=26360#c4
	    ENABLE_OBSOLETE="--with-long-double-128"
	    LIBSSP_CONFIG="--disable-libssp"
	    ;;
	"riscv64")
	    # see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90419#c1
	    MULTILIB_CONFIG="--enable-multilib --with-multilib-list=lp64d"
	    ;;
	"tilegx")
	    MULTILIB_CONFIG="--disable-multilib"
	    ;;
	"x86_64")
	    MULTILIB_CONFIG="--enable-multilib --with-multilib-list=m64,m32,mx32"
	    ;;
    esac
    MAKE_TARGET=
    INSTALL_TARGET="install"
    case "${STAGE}" in
	"newlib")
	    LIBC_CONFIGS="--with-newlib --disable-threads"
	    LIBSSP_CONFIG="--disable-libssp"
	    ;;
	"mingw64-minimal")
	    MAKE_TARGET="all-gcc"
	    INSTALL_TARGET="install-gcc"
	    ;;
	"uclibc")
	    if [ -z "${UCLIBC_WANTS_NPTL}" -a -z "${UCLIBC_WANTS_LINUXTHREADS}" ]; then
		LIBC_CONFIGS="--disable-threads"
	    fi
	    if [ -z "${UCLIBC_WANTS_SSP}" ]; then
		LIBSSP_CONFIG="--disable-libssp"
	    fi
	    ;;
    esac
    unpack_tarball "gcc-${GCC_VSN}"
    rm -rf objdir-gcc
    mkdir objdir-gcc
    cd objdir-gcc
    ${SOURCES_DIR}/gcc-${GCC_VSN}/configure \
		--target="${TARGET_TRIPLE}" ${ENABLE_OBSOLETE} \
		--build="${BUILD_TRIPLE}" \
		--prefix="${CROSS_DIR}" \
		--with-sysroot="${CROSS_DIR}" \
		--with-gmp="${HOST_TOOLS_DIR}/gmp-${GMP_VSN}${SUFFIX}" \
		--with-mpfr="${HOST_TOOLS_DIR}/mpfr-${MPFR_VSN}${SUFFIX}" \
		--with-mpc="${HOST_TOOLS_DIR}/mpc-${MPC_VSN}${SUFFIX}" \
		--without-isl \
		--disable-libatomic \
		--disable-libgomp \
		--disable-libitm \
		--disable-libmpx \
		--disable-libquadmath \
		--disable-libsanitizer \
		--disable-lto \
		--disable-nls \
		--disable-plugin \
		--disable-shared \
	        ${ENABLE_CHECKING} \
		--enable-languages=c \
		${MULTILIB_CONFIG} \
		${LIBC_CONFIGS} ${LIBSSP_CONFIG}
    make ${DASHJ} ${MAKE_TARGET}
    make ${INSTALL_TARGET}
    touch "${CROSS_DIR}/.stage-gcc-${STAGE}"
    cd ..
    rm -rf objdir-gcc
}

build_cross_gcc_without_libc() {
    if [ -n "${MINGW64_VSN}" ]; then
	build_cross_gcc "mingw64-minimal"
    else
	build_cross_gcc "newlib"
    fi
}

build_cross_gcc_with_libc() {
    if [ -n "${GLIBC_VSN}" ]; then
	build_cross_gcc "glibc"
    elif [ -n "${UCLIBC_VSN}" ]; then
	build_cross_gcc "uclibc"
    elif [ -n "${MUSL_VSN}" ]; then
	build_cross_gcc "musl"
    elif [ -n "${MINGW64_VSN}" ]; then
	 build_cross_gcc "mingw64-full"
    elif [ -n "${NEWLIB_VSN}" ]; then
	: nothing to do
    fi
}

build_cross_binutils() {
    local ENABLE_TARGETS
    local ENABLE_OBSOLETE
    if [ -x "${CROSS_DIR}/bin/${TARGET_TRIPLE}-as" ]; then
	return
    fi
    log "building cross-binutils-${BINUTILS_VSN}"
    ENABLE_TARGETS=
    case "${TARGET_ARCH}" in
	"mingw64")
	    ENABLE_TARGETS="--enable-targets=x86_64-w64-mingw32,i686-w64-mingw32"
	    ;;
    esac
    ENABLE_OBSOLETE=
    if [ -n "${BINUTILS_WANTS_ENABLE_OBSOLETE}" ]; then
	ENABLE_OBSOLETE="--enable-obsolete"
    fi
    unpack_tarball "binutils-${BINUTILS_VSN}"
    rm -rf objdir-binutils
    mkdir objdir-binutils
    cd objdir-binutils
    ${SOURCES_DIR}/binutils-${BINUTILS_VSN}/configure \
		--target="${TARGET_TRIPLE}" ${ENABLE_TARGETS} ${ENABLE_OBSOLETE} \
		--build="${BUILD_TRIPLE}" \
		--prefix="${CROSS_DIR}" \
		--with-sysroot="${CROSS_DIR}" \
		--disable-gold \
		--disable-nls \
		--disable-plugins
    make ${DASHJ}
    make MAKEINFO=/bin/true install
    cd ..
    rm -rf objdir-binutils
}

build_linux_headers() {
    local KERNEL_ARCH
    if [ -f "${CROSS_DIR}/usr/include/linux/version.h" ]; then
	return
    fi
    log "building linux-headers-${LINUX_VSN}"
    case "${TARGET_ARCH}" in
	"aarch64") KERNEL_ARCH="arm64";;
	"armv7l") KERNEL_ARCH="arm";;
	"bfin") KERNEL_ARCH="blackfin";;
	"hppa") KERNEL_ARCH="parisc";;
	"mips64") KERNEL_ARCH="mips";;
	ppc64*) KERNEL_ARCH="powerpc";;
	"riscv64") KERNEL_ARCH="riscv";;
	"s390x") KERNEL_ARCH="s390";;
	"sh4") KERNEL_ARCH="sh";;
	"sparc64") KERNEL_ARCH="sparc";;
	"x86_64") KERNEL_ARCH="x86";;
	*) KERNEL_ARCH="${TARGET_ARCH}"
    esac
    unpack_tarball "linux-${LINUX_VSN}"
    cd "${SOURCES_DIR}/linux-${LINUX_VSN}"
    make ARCH="${KERNEL_ARCH}" INSTALL_HDR_PATH="${CROSS_DIR}/usr" headers_install
    make mrproper
    cd -
}

build_mingw64_headers() {
    if [ -f "${CROSS_DIR}/${TARGET_TRIPLE}/include/windows.h" ]; then
	return
    fi
    log "building mingw-w64-headers ${MINGW64_VSN}"
    unpack_tarball "mingw-w64-v${MINGW64_VSN}"
    rm -rf objdir-headers
    mkdir objdir-headers
    cd objdir-headers
    ${SOURCES_DIR}/mingw-w64-v${MINGW64_VSN}/mingw-w64-headers/configure \
		--prefix="${CROSS_DIR}/${TARGET_TRIPLE}" \
		--host="${TARGET_TRIPLE}"
    ln -sf "${TARGET_TRIPLE}" "${CROSS_DIR}/mingw"
    make install
    cd ..
    rm -rf objdir-headers
}

build_glibc() {
    local TARGET_TRIPLE="$1"
    local TARGET_CC="$2"
    log "building glibc-${GLIBC_VSN} for ${TARGET_TRIPLE} ${TARGET_CC}"
    rm -rf "${TARGET_TRIPLE}"
    mkdir "${TARGET_TRIPLE}"
    cd "${TARGET_TRIPLE}"
    ${SOURCES_DIR}/glibc-${GLIBC_VSN}/configure "${TARGET_CC}" \
		CXX=/bin/false \
		--host="${TARGET_TRIPLE}" \
		--build="${BUILD_TRIPLE}" \
		--prefix=/usr \
		--without-cvs \
		--disable-profile
    make ${DASHJ}
    make DESTDIR="${CROSS_DIR}" install
    cd ..
    rm -rf "${TARGET_TRIPLE}"
}

build_target_glibc() {
    local TARGET_CC
    unpack_tarball "glibc-${GLIBC_VSN}"
    rm -rf objdir-glibc
    mkdir objdir-glibc
    cd objdir-glibc
    # build extra glibcs for alternative ABIs like -m32
    case "${TARGET_ARCH}" in
	"mips64")
	    build_glibc "mips-unknown-linux-gnu" "CC=mips64-unknown-linux-gnu-gcc -mabi=32"
	    build_glibc "mips-unknown-linux-gnu" "CC=mips64-unknown-linux-gnu-gcc -mabi=n32"
	    TARGET_CC="CC=mips64-unknown-linux-gnu-gcc -mabi=64"
	    ;;
	"ppc64")
	    build_glibc "ppc-unknown-linux-gnu" "CC=ppc64-unknown-linux-gnu-gcc -m32"
	    ;;
	"s390x")
	    build_glibc "s390-unknown-linux-gnu" "CC=s390x-unknown-linux-gnu-gcc -m31"
	    ;;
	"sparc64")
	    build_glibc "sparcv9-unknown-linux-gnu" "CC=sparc64-unknown-linux-gnu-gcc -m32 -mcpu=ultrasparc"
	    ;;
	"x86_64")
	    build_glibc "i686-unknown-linux-gnu" "CC=x86_64-unknown-linux-gnu-gcc -m32"
	    build_glibc "x86_64-unknown-linux-gnu" "CC=x86_64-unknown-linux-gnu-gcc -mx32"
	    ;;
    esac
    # build main glibc
    build_glibc "${TARGET_TRIPLE}" "${TARGET_CC}"
    cd ..
    rm -rf objdir-glibc
}

build_target_uclibc() {
    local CROSS_COMPILE="${TARGET_TRIPLE}-"
    log "building uClibc-ng-${UCLIBC_VSN} for ${TARGET_TRIPLE}"
    unpack_tarball "uClibc-ng-${UCLIBC_VSN}"
    cd "${SOURCES_DIR}/uClibc-ng-${UCLIBC_VSN}"
    make clean
    if [ ! -f "extra/Configs/defconfigs/${TARGET_ARCH}/defconfig" ]; then
	mkdir -p "extra/Configs/defconfigs/${TARGET_ARCH}"
	echo "TARGET_${TARGET_ARCH}=y" > "extra/Configs/defconfigs/${TARGET_ARCH}/defconfig"
    fi
    make TARGET_ARCH="${TARGET_ARCH}" CROSS_COMPILE="${CROSS_COMPILE}" defconfig
    sed -i -e s,\^KERNEL_HEADERS=.\*\$,KERNEL_HEADERS=\"${CROSS_DIR}/usr/include\",g .config
    sed -i -e s,\^RUNTIME_PREFIX=.\*\$,RUNTIME_PREFIX=\"/\",g .config
    sed -i -e s,\^DEVEL_PREFIX=.\*\$,DEVEL_PREFIX=\"/usr\",g .config
    sed -i -e s,\^CROSS_COMPILER_PREFIX=.\*\$,CROSS_COMPILER_PREFIX=\"${CROSS_COMPILE}\",g .config
    case "${TARGET_ARCH}" in
	"cris")
	    echo 'CONFIG_CRISV32=y' >> .config
	    ;;
    esac
    if [ -n "${UCLIBC_WANTS_NPTL}" ]; then
	echo 'UCLIBC_HAS_THREADS_NATIVE=y' >> .config
    elif [ -n "${UCLIBC_WANTS_LINUXTHREADS}" ]; then
	echo 'UCLIBC_HAS_LINUXTHREADS=y' >> .config
    fi
    if [ -n "${UCLIBC_WANTS_SSP}" ]; then
	echo 'UCLIBC_HAS_SSP=y' >> .config
    fi
    if [ -n "${UCLIBC_WANTS_LITTLE_ENDIAN}" ]; then
	echo 'ARCH_WANTS_BIG_ENDIAN=n' >> .config
	echo 'ARCH_WANTS_LITTLE_ENDIAN=y' >> .config
    elif [ -n "${UCLIBC_WANTS_BIG_ENDIAN}" ]; then
	echo 'ARCH_WANTS_LITTLE_ENDIAN=n' >> .config
	echo 'ARCH_WANTS_BIG_ENDIAN=y' >> .config
    fi
    make TARGET_ARCH="${TARGET_ARCH}" CROSS_COMPILE="${CROSS_COMPILE}" olddefconfig
    make ${DASHJ}
    make PREFIX="${CROSS_DIR}" install
    cp .config "${CROSS_DIR}"
    make clean
    cd -
}

build_target_musl() {
    log "building musl-${MUSL_VSN} for ${TARGET_TRIPLE}"
    unpack_tarball "musl-${MUSL_VSN}"
    rm -rf objdir-musl
    mkdir objdir-musl
    cd objdir-musl
    ${SOURCES_DIR}/musl-${MUSL_VSN}/configure \
		--host="${TARGET_TRIPLE}" \
		--build="${BUILD_TRIPLE}" \
		--prefix=/usr \
		--disable-wrapper
    make ${DASHJ}
    make DESTDIR="${CROSS_DIR}" install
    # fix lib/ld-musl-*.so.1 -> /usr/lib/libc.so symlink
    ln -sf ../usr/lib/libc.so ${CROSS_DIR}/lib/ld-musl-*.so.*
    cd ..
    rm -rf objdir-musl
}

build_target_mingw64crt() {
    log "building mingw-w64-crt ${MINGW64_VSN}"
    unpack_tarball "mingw-w64-v${MINGW64_VSN}"
    rm -rf objdir-crt
    mkdir objdir-crt
    cd objdir-crt
    ${SOURCES_DIR}/mingw-w64-v${MINGW64_VSN}/mingw-w64-crt/configure \
		--prefix="${CROSS_DIR}/${TARGET_TRIPLE}" \
		--enable-lib32 \
		--enable-lib64 \
		--host="${TARGET_TRIPLE}"
    make ${DASHJ}
    make install
    cd ..
    rm -rf objdir-crt
}

build_target_newlib() {
    log "building newlib-${NEWLIB_VSN} for ${TARGET_TRIPLE}"
    unpack_tarball "newlib-${NEWLIB_VSN}"
    rm -rf objdir-newlib
    mkdir objdir-newlib
    cd objdir-newlib
    ${SOURCES_DIR}/newlib-${NEWLIB_VSN}/configure \
		--target="${TARGET_TRIPLE}" \
		--build="${BUILD_TRIPLE}" \
		--prefix=/
    make ${DASHJ}
    make DESTDIR="${CROSS_DIR}" install
    cd ..
    rm -rf objdir-newlib
}

build_target_libc() {
    if [ -n "${GLIBC_VSN}" ]; then
	build_target_glibc
    elif [ -n "${UCLIBC_VSN}" ]; then
	 build_target_uclibc
    elif [ -n "${MUSL_VSN}" ]; then
	 build_target_musl
    elif [ -n "${MINGW64_VSN}" ]; then
	build_target_mingw64crt
    elif [ -n "${NEWLIB_VSN}" ]; then
	build_target_newlib
    fi
}

log "buildcross ${VERSION} building toolchain for ${TARGET_ARCH} in ${CROSS_DIR}"

#
# Get Sources
#

if [ ! -d "${DOWNLOADS_DIR}" ]; then
    mkdir -p "${DOWNLOADS_DIR}"
fi
if [ ! -d "${SOURCES_DIR}" ]; then
    mkdir -p "${SOURCES_DIR}"
fi

get_sources

cd ${BUILD_DIR}

#
# Build Host GCC
#

ORIG_PATH="${PATH}"

if [ -z "${SKIP_HOST_TOOLS}" ]; then

# build preliminary host libraries and gcc using system cc
build_host_gmp "-cc"
build_host_mpfr "-cc"
build_host_mpc "-cc"
build_host_gcc "-cc"

# update PATH to pick up our preliminary host gcc
export PATH="${HOST_TOOLS_DIR}/gcc-${GCC_VSN}-cc/bin:${ORIG_PATH}"

# build final host libraries and gcc using preliminary host gcc
build_host_gmp
build_host_mpfr
build_host_mpc
build_host_gcc

# remove preliminary host libraries and gcc
rm -rf ${HOST_TOOLS_DIR}/gmp-${GMP_VSN}-cc
rm -rf ${HOST_TOOLS_DIR}/mpfr-${MPFR_VSN}-cc
rm -rf ${HOST_TOOLS_DIR}/mpc-${MPC_VSN}-cc
rm -rf ${HOST_TOOLS_DIR}/gcc-${GCC_VSN}-cc

# update PATH to pick up our final host gcc
export PATH="${HOST_TOOLS_DIR}/gcc-${GCC_VSN}/bin:${ORIG_PATH}"

fi # SKIP_HOST_TOOLS

# determine BUILD_TRIPLE, ensure it differs from TARGET_TRIPLE
if [ -z "${BUILD_TRIPLE}" ]; then
    BUILD_TRIPLE=`gcc -v 2>&1 | grep '^Target:' | awk '{print $2}'`
else
    echo using BUILD_TRIPLE "${BUILD_TRIPLE}"
fi
if [ -z "${BUILD_TRIPLE}" ]; then
    echo unable to determine build triple
    exit 1
fi
if [ "${BUILD_TRIPLE}" = "${TARGET_TRIPLE}" ]; then
    echo build triple "${BUILD_TRIPLE}" equals target triple
    exit 1
fi

#
# Build Cross Tools and Libc
#

# build cross binutils
build_cross_binutils

# update PATH to pick up our cross tools
export PATH="${CROSS_DIR}/bin:${HOST_TOOLS_DIR}/gcc-${GCC_VSN}/bin:${ORIG_PATH}"

# mingw-w64 needs headers early on
[ -n "${MINGW64_VSN}" ] && build_mingw64_headers

# build preliminary cross gcc without target libc
build_cross_gcc_without_libc

# build target kernel headers
[ -n "${LINUX_VSN}" ] && build_linux_headers

# build target libc
build_target_libc

# build final cross gcc with target libc
build_cross_gcc_with_libc

log "done"
